# Generated by Django 3.0.5 on 2020-06-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totaltest', models.IntegerField(default=0)),
                ('totalpositive', models.IntegerField(default=0)),
                ('totalcollection', models.IntegerField(default=0)),
                ('date', models.CharField(default='_', max_length=20)),
            ],
        ),
    ]
